### ISSUE TITLE
Content not loaded when moved to absolute bottom

### ISSUE THREAD

**Issue by natashajaved** [onderonur/react-infinite-scroll-hook#18]
When I move to the bottom of the page in your demo then if the list items are not loaded, I have to move back to where the text "footer" is written and then it loads more item

**Comment by onderonur** [comment]
Hi!

I've just published a new major version (v4) and migrated completely to using `IntersectionObserver`.  
I guess this issue is fixed with this new version, but if you can try it too, that would be very nice to be sure 🙂.

New demo is [here](https://onderonur.github.io/react-infinite-scroll-hook/) and now we have lists with different layouts.

I'm closing this issue for now. You can reopen it anytime you find this problem pops up again 🙂.

Thanks!

**Comment by natashajaved** [comment]
Yes it is working now👍
