### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by awingmawe** [onderonur/react-infinite-scroll-hook#27]
Hello, could you help me out why i cant use this library ? i just import it to my file but it seems doesn't work well. 
The error says :
` Line 16:5:   'hasNextPage' is not defined  no-undef`
  `Line 17:17:  'loadMore' is not defined     no-undef`
  `Line 18:17:  'error' is not defined        no-undef`
  `Line 67:32:  'hasNextPage' is not defined  no-undef`

Thank you.

**Comment by onderonur** [comment]
Hi,

Can you create a simple reproduction for this issue? A simple repo, codepen demo etc. would be enough to identify the problem.

Thanks!

**Comment by awingmawe** [comment]
https://codepen.io/mochrafi007/pen/VwWjZGO this code where i need the infinite scroll, but the problem is the import cant read from this library. 

is this enough to identify the problem ? 
Im sorry this is my first time share my code with codepen..

**Comment by onderonur** [comment]
Yes, this is enough to identify the problem. Thanks for sharing the code.

The problem here is, you need to provide `loadMore`, `error` and `hasNextPage` yourself. Your code doesn't create/initialize these anywhere and uses them as parameters of `useInfiniteScroll` hook.

If you check out the `examples` folder of this repository you can see that these are coming from `useLoadItems` hook. And that is just a custom hook which is not included in this package. You can also check out [other examples](https://github.com/onderonur/react-infinite-scroll-hook#other-examples) section of `README.md` and see examples with `swr` and `Apollo GraphQL`.

Thanks!
