### ISSUE TITLE
consider exporting IntersectionObserverHookRefCallback

### ISSUE THREAD

**Issue by justin-barca-at-camis** [onderonur/react-infinite-scroll-hook#30]
In order to keep results list pure, I use the sentryRef as a prop in TS. However, I can't define the type for this prop unless I install `react-intersection-observer-hook` and import ` IntersectionObserverHookRefCallback` from there. Please consider exporting this in your library.

**Comment by onderonur** [comment]
Hi there 👋 

Thanks for the heads up. Most of the times I just do something like
```ts
import useInfiniteScroll, {
  UseInfiniteScrollHookResult,
} from 'react-infinite-scroll-hook';

type SentryRef = UseInfiniteScrollHookResult[0];
```

for this kind of cases.
Or just import it from `react-intersection-observer-hook`, which is already installed to the app because it's a dependency of `react-infinite-scroll-hook`. So, you don't need to install it separately. It's already there, but I get that some toolings/linters etc. may throw some errors/warnings for this kind of stuff.

I will make this update when I'm available.

Thanks again!

**Comment by onderonur** [comment]
And it's done with `v4.0.2` 🎉 
You can check [releases](https://github.com/onderonur/react-infinite-scroll-hook/releases) to see the type names.
