### ISSUE TITLE
Load more not triggered if viewport below sentry

### ISSUE THREAD

**Issue by tomkelsey** [onderonur/react-infinite-scroll-hook#33]
Hi,

Thanks for this project - it's very good and has been a big help!

I'm using it on a page with a big footer (below the infinite list) and so if you scroll fast you can end up below the sentry and load more is not triggered. You have to scroll back up and then down again.

You can recreate it on your demo (https://onderonur.github.io/react-infinite-scroll-hook/) by decreasing the vertical height of the browser window and then scrolling quickly down so that only the footer is visible.

It may be the intended way for the hook to work but I wondered if perhaps the logic for loading more could be if the sentry is intersecting or if it's below the current viewport?

Many thanks!

**Comment by onderonur** [comment]
Hi there,

First of all, thanks for your comments. As you can guess, this is the intended way of how this hook works. Load more only gets triggered when the sentry is visible (or it's intersecting). So a user can just scroll to the footer and see its content. Even if you have an infinite scrolling page/content, there should be a way of viewing the footer if there is one. Otherwise, what is the reason of having a footer anyway. I can guess this may not be the perfect design. But it works for many of the common cases.

If you want to trigger load more when your footer is visible and the main sentry is not visible, you can set another sentry in your footer and trigger load more in it. But I think you need to be careful to not trigger load more twice for edge cases like when the main sentry which is at the end of your infinite list and the sentry in the footer are both visible at the same time. It heavily depends on which method you are using to fetch/load more. You can deduplicate ongoing requests according to the method you choose to fetch data.

Thanks again!
