### ISSUE TITLE
Eslint issue when promises are used

### ISSUE THREAD

**Issue by neoighodaro** [onderonur/react-infinite-scroll-hook#39]
> ESLint: Promise-returning function provided to property where a void return was expected.(@typescript-eslint/no-misused-promises)

When using an async function for the `loading` property the warning above is triggered in ESLint. Of course it can be turned off but just incase you were interested. Maybe it's possible to return `void | Promise<void>`

**Comment by onderonur** [comment]
Firstly, thanks for this issue 🙏 

Recently, I've been migrating this package to use turborepo and came across the same case with `@typescript-eslint/no-misused-promises`.

I too believe it is a beneficial rule. So, providing better types instead of just turning off sounds good.

The new version which will come with monorepo migration will include this fix too. I will close this issue afterwards.

**Comment by onderonur** [comment]
Hi again 👋 

I've just published `v5.0.0` which also has the fix for this typing issue.

Thanks again 🙏
