### ISSUE TITLE
How to control list scroll to top

### ISSUE THREAD

**Issue by SteveSuv** [onderonur/react-infinite-scroll-hook#40]
```ts
function InfiniteListWithVerticalScroll(props:{id:string}) {
  const { loading, items, hasNextPage, error, loadMore } = useLoadItems();

  const [sentryRef, { rootRef }] = useInfiniteScroll({
    loading,
    hasNextPage,
    onLoadMore: loadMore,
    disabled: !!error,
    rootMargin: '0px 0px 400px 0px',
  });

  return (
    <ListContainer
      // This where we set our scrollable root component.
      ref={rootRef}
    >
      <List>
        {items.map((item) => (
          <ListItem key={item.key}>{item.value}</ListItem>
        ))}
        {(loading || hasNextPage) && (
          <ListItem ref={sentryRef}>
            <Loading />
          </ListItem>
        )}
      </List>
    </ListContainer>
  );
}
```

For example, I add rootRef to ListContainer, but when the props change, I need to control list scroll to top, I will write this:

```ts
 useEffect(() => {
    rootRef?.current.scrollTo(0, 0);
  }, [props.id, rootRef]);
```
But I can't get `rootRef?.current`. What should I do?

**Comment by onderonur** [comment]
Hello there 👋

In a way, this question is actually about how you can use ref callbacks, rather than 100% related to this package.

But I totally understand it can be tricky to figure out using multiple refs on a single component/HTML element sometimes 👍

`rootRef` returned by `useInfiniteScroll` hook is not a `ref` object like the ones created by using `useRef`. It is a "ref callback" function. It accepts a single parameter (which can be the scrollable DOM element or `null`) and uses it internally to handle infinite scrolling behavior.

So, it doesn't have a `current` property to access the underlying DOM element etc.

We need to call `rootRef` by passing the scrollable DOM element to it and also assign it to the `current` property of a `ref` object.

We can do it like this:

```tsx
function InfiniteListWithVerticalScroll(props: { id: string }) {
  const { loading, items, hasNextPage, error, loadMore } = useLoadItems();

  const [sentryRef, { rootRef }] = useInfiniteScroll({
    loading,
    hasNextPage,
    onLoadMore: loadMore,
    disabled: !!error,
    rootMargin: "0px 0px 400px 0px",
  });

  // 👀 Declare a ref object to manipulate scrolling.
  const scrollableRef = useRef<React.ElementRef<typeof ListContainer> | null>(null);

  // 👀 Create a new ref callback to set both `rootRef` and `scrollableRef`.
  const rootRefSetter = useCallback(
    (node: React.ElementRef<typeof ListContainer> | null) => {
      rootRef(node);
      scrollableRef.current = node;
    },
    [rootRef]
  );

  // 👀 Change scroll position on `id` change.
  useEffect(() => {
    scrollableRef.current?.scrollTo(0, 0);
  }, [props.id]);

  return (
    <ListContainer
      // 👀 Pass the new ref callback to the scrollable container.
      ref={rootRefSetter}
    >
      <List>
        {items.map((item) => (
          <ListItem key={item.key}>{item.value}</ListItem>
        ))}
        {(loading || hasNextPage) && (
          <ListItem ref={sentryRef}>
            <Loading />
          </ListItem>
        )}
      </List>
    </ListContainer>
  );
}
```

There are also very similar usages in `demo` app of this package:

- https://github.com/onderonur/react-infinite-scroll-hook/blob/main/apps/demo/src/components/infinite-list-with-reverse-vertical-scroll.tsx
- https://github.com/onderonur/react-infinite-scroll-hook/blob/main/apps/demo/src/components/infinite-list-with-reverse-horizontal-scroll.tsx

And if you want more information on this topic, [Manipulating the DOM with Refs](https://react.dev/learn/manipulating-the-dom-with-refs) in official React docs explains it very well.

Thanks 🙏
